#source :rubygems

#gem 'rake', ' 0.8.7'
#gem 'rails', '2.1.0'
#gem 'rails', '3.1.0'

source 'http://rubygems.org'

gem 'rails', '3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

gem 'jquery-rails'

gem 'omniauth'


# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  gem  'mocha' , "0.10.0", :require => false
  # Pretty printed test output
  gem 'turn', :require => false
  gem "rspec-rails", "~> 2.6"
  # gem 'autotest'
  # gem 'autotest-rails'
  # gem 'autotest-notification'  #for growl like notifications popup window
  gem 'factory_girl_rails'
  gem 'faker'
  gem "spork", "> 0.9.0.rc"
  gem "guard-spork"
  gem "guard-rspec"
end

# javascript error of execjs missing for coffee script
gem 'execjs'
gem 'therubyracer'
                                                                                                                                                                                                                                                                                                   
gem 'sqlite3'

